services:
    melodiia.configuration:
        class: SwagIndustries\Melodiia\MelodiiaConfiguration
        arguments:
            $config: '%melodiia.config%'

    # Priority -1 is DX. It allow the user to implement its own normalizers
    # that will take over those.
    melodiia.serialization.created_normalizer:
        class: SwagIndustries\Melodiia\Serialization\Json\CreatedNormalizer
        tags: [{ name: 'serializer.normalizer', priority: -1 }]

    melodiia.serialization.error_normalizer:
        class: SwagIndustries\Melodiia\Serialization\Json\ErrorNormalizer
        tags: [{ name: 'serializer.normalizer', priority: -1 }]

    melodiia.serialization.ok_content_normalizer:
        class: SwagIndustries\Melodiia\Serialization\Json\OkContentNormalizer
        autoconfigure: true
        arguments:
            $requestStack: '@request_stack'
        tags: [{ name: 'serializer.normalizer', priority: -1 }]

    SwagIndustries\Melodiia\MelodiiaConfigurationInterface: '@melodiia.configuration'

    melodiia.response_listener:
        class: SwagIndustries\Melodiia\Response\Listener\SerializeOnKernelView
        autoconfigure: true
        autowire: true
        arguments:
            $contextBuilderChain: '@melodiia.context_builder_chain'

    melodiia.context_builder_chain:
        class: SwagIndustries\Melodiia\Serialization\Context\ContextBuilderChain
        arguments:
            $builders: !tagged_iterator melodiia.context_builder

