services:
    melodiia.doctrine.data_provider:
        class: SwagIndustries\Melodiia\Bridge\Doctrine\DoctrineDataStore
        arguments:
            $registry: '@doctrine'

    melodiia.crud.id_resolver:
        class: SwagIndustries\Melodiia\Crud\Tools\SimpleIdResolver

    melodiia.crud.filters.filter_collection_factory:
        class: SwagIndustries\Melodiia\Crud\FilterCollectionFactory
        arguments:
            $formFactory: '@form.factory'
            $filters: !tagged melodiia.crud_filter

    SwagIndustries\Melodiia\Crud\Pagination\PaginationRequestFactoryInterface:
        alias: 'melodiia.crud.pagination.pages_request_factory'

    melodiia.crud.pagination.pages_request_factory:
        class: SwagIndustries\Melodiia\Crud\Pagination\PaginationRequestFactory
        arguments:
            $configuration: '@melodiia.configuration'

    melodiia.crud.controller.create:
        class: SwagIndustries\Melodiia\Crud\Controller\Create
        arguments:
            $dataStore: '@melodiia.doctrine.data_provider'
            $formFactory: '@form.factory'
            $dispatcher: '@event_dispatcher'
            $checker: '@security.authorization_checker'
        tags: [ controller.service_arguments ]

    melodiia.crud.controller.update:
        class: SwagIndustries\Melodiia\Crud\Controller\Update
        arguments:
            $dataStore: '@melodiia.doctrine.data_provider'
            $formFactory: '@form.factory'
            $dispatcher: '@event_dispatcher'
            $checker: '@security.authorization_checker'
            $idResolver: '@melodiia.crud.id_resolver'
        tags: [ controller.service_arguments ]

    melodiia.crud.controller.get_all:
        class: SwagIndustries\Melodiia\Crud\Controller\GetAll
        arguments:
            $dataStore: '@melodiia.doctrine.data_provider'
            $checker: '@security.authorization_checker'
            $collectionFactory: '@melodiia.crud.filters.filter_collection_factory'
            $pagesRequestFactory: '@SwagIndustries\Melodiia\Crud\Pagination\PaginationRequestFactoryInterface'
        tags: [ controller.service_arguments ]

    melodiia.crud.controller.get:
        class: SwagIndustries\Melodiia\Crud\Controller\Get
        arguments:
            $dataStore: '@melodiia.doctrine.data_provider'
            $checker: '@security.authorization_checker'
            $idResolver: '@melodiia.crud.id_resolver'
        tags: [ controller.service_arguments ]

    melodiia.crud.controller.delete:
        class: SwagIndustries\Melodiia\Crud\Controller\Delete
        arguments:
            $dataStore: '@melodiia.doctrine.data_provider'
            $checker: '@security.authorization_checker'
            $dispatcher: '@event_dispatcher'
            $idResolver: '@melodiia.crud.id_resolver'
        tags: [ controller.service_arguments ]
