services:
    melodiia.exception.controller:
        class: Biig\Melodiia\Error\OnError
        arguments:
            $serializer: '@serializer'

    melodiia.exception.listener:
        class: Biig\Melodiia\Bridge\Symfony\EventListener\ExceptionListener
        arguments:
            $config: '@melodiia.configuration'
            $controller: '@melodiia.exception.controller'
            $logger: '@logger'
        tags:
            - { name: 'kernel.event_listener', event: kernel.exception, method: onKernelException, priority: -96 }
            - { name: 'monolog.logger', channel: 'request' }

    melodiia.exception.normalizer:
        class: Biig\Melodiia\Serialization\Json\ExceptionNormalizer
        arguments:
            $debug: '%kernel.debug%'
        tags: [{ name: 'serializer.normalizer', priority: -1 }]
