services:
    happii.routing_loader:
        class: Biig\Happii\Bridge\Symfony\Routing\LoadGeneratedRoutes
        public: true
        arguments:
            $config: '@happii.configuration'

    happii.configuration:
        class: Biig\Happii\Bridge\Symfony\HappiConfiguration
        arguments:
            $config: '%happii.config%'

    happii.serialization.created_normalizer:
        class: Biig\Happii\Serialization\Json\CreatedNormalizer
        tags: { name: 'serializer.normalizer' }

    happii.serialization.error_normalizer:
        class: Biig\Happii\Serialization\Json\ErrorNormalizer
        tags: { name: 'serializer.normalizer' }

    Biig\Happii\HappiiConfigurationInterface: '@happii.configuration'
